name: Update README and create PR

on:
  workflow_dispatch:  # You can also use `push` or a cron schedule

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Modify README
        run: |
          echo "### Updated on $(date)" >> README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update README with timestamp"
          title: "Update README with latest timestamp"
          body: |
            This PR updates the `README.md` file with the latest timestamp.
          branch: update-readme-$(date +%s)
